<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>YoutubePlugin</AssemblyName>
    <RootNamespace>Manitux.YoutubePlugin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Manitux.Core/Manitux.Core.csproj" />
  </ItemGroup>

</Project>
